### ISSUE TITLE
Check compatibility with OTP for the websites

### ISSUE THREAD

**Issue by mfr-itr** [bitwarden/jslib#11]
(Not sure if this issue should be on this repo)

It would be cool if bitwarden would suggest to add TOTP 2FA for websites that support it. Maybe using https://twofactorauth.org/data.json. It could be added as a note when you view a compatible website, plus new tool to view the OTP status for all the compatible sites

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
