### ISSUE TITLE
Add Dashlane CSV Importer

### ISSUE THREAD

**Issue by ArnaudBan** [bitwarden/jslib#36]
You can already import Dashlane JSON file but not Dashlane CSV file.

I am making this request because i can't export my Dashlane passwords in JSON format. There is a bug in Dashlane that export both JSON and CSV option in CSV file.

Please add a Dashlane CSV import so i can import all my password in Bitwarden !

**Comment by kspearrin** [comment]
Dashlane's CSV export does not provide a structure that can be accurately parsed. We used to have an importer for it, but it was removed in favor of the JSON version, which is well structured.

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
